services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '3000:3000'
    depends_on:
      - redis
    volumes:
      - ./src:/app/src

  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
